name: ai-logistic-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy>=1.19.0
  - pandas>=1.1.0
  - matplotlib>=3.0.0
  - scikit-learn>=0.24.0

# Installation:
# conda env create -f environment.yml
# conda activate ai-logistic-regression

# Description:
# Environment for COMP 237 Assignment 4 - Logistic Regression
# Titanic survival prediction using binary classification
# Includes data visualization, preprocessing, and model evaluation