name: ai-logistic-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.1
  - scikit-learn=1.2.2

# Installation:
# conda env create -f environment.yml
# conda activate ai-logistic-regression

# Description:
# Environment for COMP 237 Assignment 4 - Logistic Regression
# Titanic survival prediction using binary classification
# Includes data visualization, preprocessing, and model evaluation

# Version compatibility notes:
# - Python 3.11: Modern Python version
# - NumPy 1.23.5: Compatible with Python 3.11
# - Pandas 1.5.3: Compatible with Python 3.11 and NumPy 1.23
# - Matplotlib 3.7.1: Compatible with Python 3.11
# - Scikit-learn 1.2.2: Compatible with Python 3.11