name: dl-cnn-rnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=20.0
  - pip:
    - tensorflow>=2.8.0,<3.0.0
    - numpy>=1.19.0,<2.0.0
    - matplotlib>=3.3.0,<4.0.0
    - seaborn>=0.11.0,<1.0.0
    - scikit-learn>=0.24.0,<2.0.0