name: ai-linear-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - pip
  - pip:
    - seaborn==0.12.2

# Installation:
# conda env create -f environment.yml
# conda activate ai-linear-regression

# Update existing environment:
# conda env update -f environment.yml --prune

# Description:
# Environment for COMP 237 Assignment 3 - Linear Regression
# Python 3.11 compatible versions
# Includes data preprocessing, feature engineering, and model evaluation
# Covers noise simulation and e-commerce spending prediction

# Version compatibility notes:
# - Python 3.11: Modern Python version
# - Pandas 1.5.3: Compatible with Python 3.11 and NumPy 1.23
# - NumPy 1.23.5: Compatible with Python 3.11
# - Scikit-learn 1.2.2: Compatible with Python 3.11
# - Matplotlib 3.7.1: Compatible with Python 3.11
# - Seaborn 0.12.2: Compatible with Matplotlib 3.7