name: dl-autoencoder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=20.0
  - pip:
    - tensorflow==2.10.0
    - numpy==1.23.5
    - matplotlib==3.6.2
    - seaborn==0.12.1
    - scikit-learn==1.1.3

# Installation:
# conda env create -f environment.yml
# conda activate dl-autoencoder

# Update existing environment:
# conda env update -f environment.yml --prune

# Description:
# Environment for Deep Learning Assignment 2 - Autoencoder with Transfer Learning
# Denoising autoencoder + supervised classifier using pretrained encoder
# Demonstrated 2% improvement with unsupervised pretraining (57K samples)

# Version compatibility notes (2022 stable releases):
# - Python 3.10: Required for TensorFlow 2.10 compatibility
# - TensorFlow 2.10.0: Last TF 2.x with native Python 3.10 support (Sept 2022)
# - NumPy 1.23.5: Compatible with TensorFlow 2.10 (Nov 2022)
# - Matplotlib 3.6.2: Stable release for Python 3.10 (Nov 2022)
# - Seaborn 0.12.1: Compatible with Matplotlib 3.6 (Oct 2022)
# - Scikit-learn 1.1.3: Stable with NumPy 1.23 (Nov 2022)